using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace WhatHappen.Generators.Decorators;

public static class MarkerAttributeGenerator
{
	private const string Namespace = "DecoratorsGenerators";
	private const string AttributeName = "GenerateTrackAttribute";
	private const string AttributeSourceCode = $@"// <auto-generated/>

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Interface)]
    public class {AttributeName} : System.Attribute
    {{
    }}
}}";

	public static void Generate(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"GenerateTrackAttribute.g.cs",
			SourceText.From(AttributeSourceCode, Encoding.UTF8)));
	}

	public static bool IsMarkerAttribute(string attributeDeclaration)
	{
		return attributeDeclaration == $"{Namespace}.{AttributeName}";
	}
}